name = "ncpa-notes-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "ncpa-notes"
database_id = "1966b0e8-c79c-4b04-b404-53bb4c11f30e"

# CORS settings
[env.production]
